remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

# This is YOUR information
title: "My Awesome Portfolio"  # The big name at the top of your site
description: "A site to show off my projects and ideas." # The subtitle under the title
show_downloads: false # Hides the "Download" button if you don't need it
